services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${METEEN_DB_PASS}"
      POSTGRES_USER: "${METEEN_DB_USER}"
      POSTGRES_DB: "${METEEN_DB_NAME}"
    networks:
      - db
    ports:
      - "5432:5432"
  dbmon:
    image: elestio/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "a@a.a"
      PGADMIN_DEFAULT_PASSWORD: "a"
      PGADMIN_LISTEN_PORT: 8080
    networks:
      - db
    ports:
      - "8080:8080"

networks:
  db:
    driver: bridge
