[package]
name = "meteen-model"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
serde = { version = "1.0.208", features = ["derive"] }
thiserror = "1.0.63"
tracing = "0.1.40"
